# Lab 2 Task (InClass)


> Create a 1 Dimentional Matrix with 20 Elements and Reshape it to 2 Dimentional (4,5)

> Check and Print all Matrix with Dimention 

> Print Shape

> Print Type

> Find Mean with Row and Colum wise

> Find Maximum, Minimum, std Devietion and Varience

In [1]:
import numpy as np

In [2]:
M = np.arange(20)
M

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
M.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
M.ndim

1

In [6]:
N = M.reshape(4,5)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
N.ndim

2

In [8]:
N.shape

(4, 5)

In [9]:
N.dtype

dtype('int64')

In [10]:
N.mean(axis = 0) #Column wise mean

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [11]:
N.mean(axis =1)

array([ 2.,  7., 12., 17.])

In [12]:
N.max()

19

In [13]:
N.min()

0

In [14]:
N.sum()

190

In [16]:
N.std()

5.766281297335398

In [17]:
N.var()

33.25